//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int admin_id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Email { get; set; }
        public string Secondary_Email { get; set; }
        public string Password { get; set; }
        public string Confirm_Password { get; set; }
        public string Phone_Number { get; set; }
        public string Phone_Number_Country_Code { get; set; }
        public string Profile_Picture { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Deactivated_Date { get; set; }
        public Nullable<int> Deactivated_By { get; set; }
        public bool IsActive { get; set; }
    }
}
