//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerReq
    {
        public int buyer_req_id { get; set; }
        public int user_id { get; set; }
        public int note_id { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> Req_Created_Date { get; set; }
        public Nullable<System.DateTime> Req_Solved_Date { get; set; }
    
        public virtual NoteDetail NoteDetail { get; set; }
        public virtual User User { get; set; }
    }
}
