//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int review_id { get; set; }
        public int note_id { get; set; }
        public int user_id { get; set; }
        public decimal Rating { get; set; }
        public string Comment { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<System.DateTime> Deactivated_Date { get; set; }
        public Nullable<int> Deactivated_By { get; set; }
        public bool IsActive { get; set; }
    
        public virtual NoteDetail NoteDetail { get; set; }
        public virtual User User { get; set; }
    }
}
